INSERT INTO AUTHORS (NAME) VALUES ('George Orwell');
INSERT INTO AUTHORS (NAME) VALUES ('J.K. Rowling');

INSERT INTO BOOKS (TITLE, AUTHOR_ID) VALUES ('1984', 1);
INSERT INTO BOOKS (TITLE, AUTHOR_ID) VALUES ('Animal Farm', 1);
INSERT INTO BOOKS (TITLE, AUTHOR_ID) VALUES ('Harry Potter', 2);
