package com.example.demo.controller;

import org.springframework.core.io.ResourceLoader;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import lombok.Getter;
import lombok.Setter;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Controller for serving JaCoCo code coverage reports.
 */
@RestController
@RequestMapping("/api/coverage")
@CrossOrigin(
        origins = {
                "http://localhost:4200",
                "http://localhost:3000",
                "https://myproject-1-vf3w.onrender.com"
        },
        methods = {RequestMethod.GET, RequestMethod.OPTIONS},
        allowedHeaders = "*",
        allowCredentials = "true"
)
public class CoverageController {

    private final ResourceLoader resourceLoader;
    private static final String JACOCO_REPORT_PATH = "target/site/jacoco/index.html";

    public CoverageController(ResourceLoader resourceLoader) {
        this.resourceLoader = resourceLoader;
    }

    /**
     * Returns the JaCoCo coverage report index.html
     */
    @GetMapping(produces = MediaType.TEXT_HTML_VALUE)
    public ResponseEntity<String> getCoverageReport() {
        try {
            Path reportPath = Paths.get(JACOCO_REPORT_PATH);
            
            if (!Files.exists(reportPath)) {
                return ResponseEntity.status(HttpStatus.NOT_FOUND)
                        .header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
                        .body("{\"error\": \"JaCoCo report not found. Please run: mvn clean test\"}");
            }

            String htmlContent = Files.readString(reportPath);
            return ResponseEntity.ok()
                    .header(HttpHeaders.CONTENT_TYPE, MediaType.TEXT_HTML_VALUE)
                    .body(htmlContent);
        } catch (IOException e) {
            return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR)
                    .header(HttpHeaders.CONTENT_TYPE, MediaType.APPLICATION_JSON_VALUE)
                    .body("{\"error\": \"Failed to read coverage report: " + e.getMessage() + "\"}");
        }
    }

    /**
     * Returns information about coverage status
     */
    @GetMapping("/status")
    public ResponseEntity<CoverageStatus> getCoverageStatus() {
        try {
            Path reportPath = Paths.get(JACOCO_REPORT_PATH);
            
            boolean exists = Files.exists(reportPath);
            long lastModified = exists ? Files.getLastModifiedTime(reportPath).toMillis() : 0;

            CoverageStatus status = new CoverageStatus(
                    exists,
                    lastModified,
                    exists ? "JaCoCo report available" : "JaCoCo report not generated. Run: mvn clean test"
            );

            return ResponseEntity.ok(status);
        } catch (IOException e) {
            return ResponseEntity.ok(new CoverageStatus(
                    false, 
                    0, 
                    "Error reading report: " + e.getMessage()
            ));
        }
    }

    /**
     * Health check endpoint
     */
    @GetMapping("/health")
    public ResponseEntity<String> health() {
        return ResponseEntity.ok("{\"status\": \"Coverage API is running\"}");
    }

    /**
     * DTO for coverage status response
     */
    @Setter
    @Getter
    public static class CoverageStatus {
        private boolean available;
        private long lastModified;
        private String message;

        public CoverageStatus(boolean available, long lastModified, String message) {
            this.available = available;
            this.lastModified = lastModified;
            this.message = message;
        }

        // Getters and setters are generated by Lombok
    }
}